
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module top (

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,

	//////////// LED //////////
	output		     [8:0]		LEDG,
	output		    [17:0]		LEDR,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		    [17:0]		SW,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,
	output		     [6:0]		HEX6,
	output		     [6:0]		HEX7
);

  logic [3:0] val0, val1, val2, val3;
  logic [3:0] val4, val5, val6, val7;

  assign val0 = SW[3:0];       // SW[3:0] -> HEX0
  assign val1 = SW[7:4];       // SW[7:4] -> HEX1
  assign val2 = SW[11:8];      // SW[11:8] -> HEX2
  assign val3 = SW[15:12];     // SW[15:12] -> HEX3
  assign val4 = SW[17:16];     // SW[17:16] -> HEX4

  assign val5 = 4'h0;
  assign val6 = 4'h0;
  assign val7 = 4'h0;

  hexdriver hd0 (.val(val0), .HEX(HEX0));
  hexdriver hd1 (.val(val1), .HEX(HEX1));
  hexdriver hd2 (.val(val2), .HEX(HEX2));
  hexdriver hd3 (.val(val3), .HEX(HEX3));
  hexdriver hd4 (.val(val4), .HEX(HEX4));
  hexdriver hd5 (.val(val5), .HEX(HEX5));
  hexdriver hd6 (.val(val6), .HEX(HEX6));
  hexdriver hd7 (.val(val7), .HEX(HEX7));
  
  cpu cpu_inst(.clk(CLOCK_50), .rst_n(KEY[0:0]), .GPIO_in({val0, val1, val2, val3, val4, val5, val6, val7}), .GPIO_out());

endmodule


